baseurl: "/"
permalink: pretty
title: "SEARCH"

logo:
  image: "/uploads/branding/logo.svg"
  height: "32px"

home:
  limit_services: 6

collections:
  team:
    output: false
  projects:
    output: true
    permalink: "/research-project/:path/"
  sprojects:
    output: true
    permalink: /student-project/:path/
  events:
    output: true
    permalink: /events/:path/
  news:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "news-post"
  - scope:
      path: ""
      type: "events"
    values:
      layout: "article"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "article"
      backlink:
        url: "/research"
        text: "All research projects"
  - scope:
      path: ""
      type: "sprojects"
    values:
      layout: "article"
      backlink:
        url: "/education"
        text: "All student projects"
  - scope:
      path: ""
      type: "team"
    values:
      image: "/assets/grahics/search-avatar.svg"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
