baseurl: "/"
permalink: pretty

logo: "/uploads/branding/logo.svg"
title: "RuG - SEARCH"
tagline: "Software Engineering and Architecture research group"
description: The vision of the RuG Software Engineering and Architecture group is that effective software engineering requires healthy software and teams. Our research enables productive, diverse and inclusive teams, as well as software that is maintainable, performant, with low technical debt, and based on sound design decisions.
author: dfeitosa
twitter:
  card: summary
  username: searchRUG

home:
  limit_services: 6

collections:
  team:
    output: false
  projects:
    output: true
    permalink: "/research/projects/:path/"
  sprojects:
    output: true
    permalink: /education/student-projects/:path/
  events:
    output: true
    permalink: /events/:path/
  news:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "article"
      showDate: true
      backlink:
        url: "/news"
        text: "All news"
  - scope:
      path: ""
      type: "events"
    values:
      layout: "article"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "article"
      backlink:
        url: "/research"
        text: "All research projects"
  - scope:
      path: ""
      type: "sprojects"
    values:
      layout: "article"
      backlink:
        url: "/education"
        text: "All student projects"
  - scope:
      path: ""
      type: "team"
    values:
      image: "/uploads/team-avatars/search-avatar.svg"
  - scope:
      path: "google91af919a735a897d.html"
    values:
      sitemap: false

plugins:
  - jekyll-environment-variables
  - jekyll-seo-tag
  - jekyll-sitemap

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
  - scripts/
  - package.json
  - package-lock.json
  - node_modules/
  - tailwind.config.js
