baseurl: "/"
permalink: pretty
title: "SEARCH"

logo:
  image: "images/logo/logo.svg"
  height: "32px"

home:
  limit_services: 6

collections:
  team:
    output: false
  projects:
    output: false
  sprojects:
    output: false
  news:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "news-post"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"
      image: "images/team/search-avatar.svg"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
