# config.yml
backend:
  name: github
  # TODO: change to 'search-rug/search-rug.github.io' when merged upstream
  repo: kakka0903/search-rug.github.io
  branch: main
media_folder: "assets/uploads"
collections:
  - name: "team"
    label: "Team Member"
    folder: "_team"
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: position, label: Position, widget: string }
